const products = [
  {
    id: 0,
    priductImg: "./assets/pic (6).jpg",
    productName: "Kabaab",
    price: 165,
    description: "Flover full Beef",
    isAdded: false,
  },
  {
    id: 1,
    priductImg: "./assets/pic (3).jpg",
    productName: "Fried Rice",
    price: 200,
    description: "originated in China",
    isAdded: false,
  },
  {
    id: 2,
    priductImg: "./assets/pic (8).jpg",
    productName: "North Thali",
    price: 145,
    description: "North Indian Tredition",
    isAdded: false,
  },
  {
    id: 3,
    priductImg: "./assets/p (1).jpg",
    productName: "Butter Naan",
    price: 30,
    description: "flatbread cooked in a tandoor",
    isAdded: false,
  },
  {
    id: 4,
    priductImg: "./assets/p (3).jpg",
    productName: "Noodles",
    price: 180,
    description: "Popular Chineese",
    isAdded: false,
  },
  {
    id: 5,
    priductImg: "./assets/pic (5).jpg",
    productName: "Prawn Fry",
    price: 320,
    description: "Lorem Ipsum...",
    isAdded: false,
  },
  {
    id: 6,
    priductImg: "./assets/pic (4).jpg",
    productName: "Broaster",
    price: 195,
    description: "Lorem Ipsum...",
    isAdded: false,
  },
  {
    id: 7,
    priductImg: "./assets/pic.jpg",
    productName: "Ghee Rice",
    price: 100,
    description: "Flover Rice",
    isAdded: false,
  },
  {
    id: 8,
    priductImg: "./assets/pi- (1).jpg",
    productName: "Fries",
    price: 45,
    description: "Lorem Ipsum...",
    isAdded: false,
  },
  {
    id: 9,
    priductImg: "./assets/pi- (4).jpg",
    productName: "Beef Burger",
    price: 150,
    description: "Lorem Ipsum...",
    isAdded: false,
  },
  {
    id: 10,
    priductImg: "./assets/pi- (2).jpg",
    productName: "Cheese Burger",
    price: 110,
    description: "Lorem Ipsum...",
    isAdded: false,
  },
  {
    id: 11,
    priductImg: "./assets/pi- (3).jpg",
    productName: "Ham Burger",
    price: 90,
    description: "Lorem Ipsum...",
    isAdded: false,
  },
];
